### ISSUE TITLE
Is this a replacement for gmenudbusmenuproxy?

### ISSUE THREAD

**Issue by probonopd** [oezingle/Simple-Appmenu-Server#1]
hello, I am working on supporting global menus properly in [helloSystem](https://hellosystem.github.io/).

Is this a replacement for gmenudbusmenuproxy?
Or how else does it fit in with all the other [apparently needed components](https://hellosystem.github.io/docs/developer/menu.html) for global menus?

Thanks!

**Comment by oezingle** [comment]
My project is kind of a replacement, I suppose. Looking at [kde's menuproxy.cpp](https://github.com/KDE/plasma-workspace/blob/master/gmenu-dbusmenu-proxy/menuproxy.cpp), their project supports a KDE-specific menu implementation whereas I rely on KDE apps porting their own menus over to the interface i do support, `com.canonical.AppMenu.Registrar`. 

This project also doesn't have any GTK or QT applet for the actual menu, as I implemented that in lua for my AwesomeWM configuration. All it really does is give apps a place to throw their menus, and then the visual (or command line, or whatever) implementation is up to you.

With this server implementation the only apps left are 'true' GTK apps, which register their menus under a different DBus interface to a DBus path based on the id of the window, which you can capture using `xprop -id <window_id> _GTK_UNIQUE_BUS_NAME` and `xprop -id <window_id> _GTK_MENUBAR_OBJECT_PATH` or similar.

If you've got any questions about my AwesomeWM menu implementation feel free to reach out
